title: Заметки Web разработчика.
description: > # this means to ignore newlines until "baseurl:"
  Сайт по web разрапотке с полезными ссылками и материалом.
permalink: ':title/'
baseurl: "/Demo-jekyll" # the subpath of your site, e.g. /blog
url: "https://proprofit.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ProProfit # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: proprofit # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
