title: ProProfit # your site title
author: Xranitel
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Немного о себе. Учусь на своих ошибках. Заметки. Примеры. Скрипты.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://proprofit.github.io/Demo-jekyll" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PRo # replace with your_twitter_username or comment to remove link from footer
github_username:  ProProfit # replace with your_github_username or comment to remove link from footer
instagram_username: 2111 # replace with your_instagram_username or comment to remove link from footer
social:
  name: Alex
  links:
    - https://twitter.com/#
    - https://www.facebook.com/#
    - https://www.linkedin.com/in/#
    - https://plus.google.com/#
    - https://github.com/#
    - https://keybase.io/#

disqus:
  shortname: w # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
